# Generated by Django 5.2.3 on 2025-06-28 05:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique code for the affiliate link', unique=True)),
                ('custom_slug', models.SlugField(blank=True, help_text='Custom slug for the affiliate link', max_length=100, null=True)),
                ('landing_url', models.URLField(blank=True, help_text='Custom landing page URL', null=True, validators=[django.core.validators.URLValidator()])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this affiliate link is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Link expiration date', null=True)),
                ('affiliate', models.ForeignKey(help_text='Affiliate who owns this link', limit_choices_to={'role': 'affiliate'}, on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_links', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='Product being promoted', on_delete=django.db.models.deletion.CASCADE, related_name='affiliate_links', to='products.product')),
            ],
            options={
                'verbose_name': 'Affiliate Link',
                'verbose_name_plural': 'Affiliate Links',
                'db_table': 'tracking_affiliate_link',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the visitor')),
                ('user_agent', models.TextField(help_text="User agent string of the visitor's browser")),
                ('referrer', models.URLField(blank=True, help_text='Referrer URL', null=True)),
                ('country', models.CharField(blank=True, help_text='Country code based on IP address', max_length=2, null=True)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', help_text='Device type detected from user agent', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the click occurred')),
                ('affiliate_link', models.ForeignKey(help_text='Affiliate link that was clicked', on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='tracking.affiliatelink')),
            ],
            options={
                'verbose_name': 'Click',
                'verbose_name_plural': 'Clicks',
                'db_table': 'tracking_click',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, help_text='External order ID from merchant system', max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Conversion amount (sale value)', max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, help_text='Commission amount for the affiliate', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Currency code', max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the conversion occurred')),
                ('verified', models.BooleanField(default=False, help_text='Whether this conversion has been verified')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the conversion')),
                ('affiliate_link', models.ForeignKey(help_text='Affiliate link that generated the conversion', on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='tracking.affiliatelink')),
                ('click', models.ForeignKey(blank=True, help_text='Original click that led to this conversion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversion', to='tracking.click')),
            ],
            options={
                'verbose_name': 'Conversion',
                'verbose_name_plural': 'Conversions',
                'db_table': 'tracking_conversion',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='affiliatelink',
            index=models.Index(fields=['code'], name='tracking_af_code_2b9286_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliatelink',
            index=models.Index(fields=['affiliate'], name='tracking_af_affilia_14160c_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliatelink',
            index=models.Index(fields=['product'], name='tracking_af_product_31e0df_idx'),
        ),
        migrations.AddIndex(
            model_name='affiliatelink',
            index=models.Index(fields=['is_active'], name='tracking_af_is_acti_905ed5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='affiliatelink',
            unique_together={('affiliate', 'product')},
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['affiliate_link'], name='tracking_cl_affilia_9516b1_idx'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['timestamp'], name='tracking_cl_timesta_33af64_idx'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['ip_address'], name='tracking_cl_ip_addr_85e748_idx'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['device_type'], name='tracking_cl_device__cfb125_idx'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['affiliate_link'], name='tracking_co_affilia_991b68_idx'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['timestamp'], name='tracking_co_timesta_f139e9_idx'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['verified'], name='tracking_co_verifie_4926f9_idx'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['order_id'], name='tracking_co_order_i_fbc576_idx'),
        ),
    ]
